import localFont from "next/font/local";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";

const hellix = localFont({
  src: [
    {
      path: "./fonts/Hellix-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Hellix-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Hellix-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Hellix-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-hellix",
});

export const metadata = {
  title: "Reckon.io",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${hellix.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
